"""adjust users

Revision ID: 4974f6f3957f
Revises: a485f7b6086d
Create Date: 2025-07-24 20:28:00.390480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4974f6f3957f'
down_revision = 'a485f7b6086d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_jti'))

    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
