"""adjust fk

Revision ID: 947afa2ca1a1
Revises: 461a4f4481ad
Create Date: 2025-07-24 16:25:55.986485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947afa2ca1a1'
down_revision = '461a4f4481ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_predictions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'weather_data', ['weather_data_id'], ['id'])

    with op.batch_alter_table('soil_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soil_type_reference_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'soil_types_reference', ['soil_type_reference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('soil_type_reference_id')

    with op.batch_alter_table('crop_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
