"""adjust users

Revision ID: b8d7eb93a534
Revises: 4974f6f3957f
Create Date: 2025-07-25 00:51:23.699402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d7eb93a534'
down_revision = '4974f6f3957f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_photos', schema=None) as batch_op:
        batch_op.alter_column('soil_analysis_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_photos', schema=None) as batch_op:
        batch_op.alter_column('soil_analysis_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
