name: Deploy Flask App to Tencent Lighthouse

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TENCENT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTHOUSE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project to Lighthouse
        run: |
          rsync -avz --exclude 'env/' --exclude '__pycache__/' --exclude '.git/' ./ ${{ secrets.TENCENT_USER }}@${{ secrets.LIGHTHOUSE_HOST }}:/home/${{ secrets.TENCENT_USER }}/gro

      - name: Deploy and setup services
        run: |
          ssh ${{ secrets.TENCENT_USER }}@${{ secrets.LIGHTHOUSE_HOST }} << 'EOF'
          cd ~/gro
          
          # Setup Python environment
          python3 -m venv env || true
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn  # Production WSGI server
          
          # Stop existing processes
          pkill -f "gunicorn.*run:app" || true
          pkill -f "python.*run.py" || true
          
          # Start Flask app with Gunicorn (production server)
          nohup env/bin/gunicorn --bind 127.0.0.1:5000 --workers 2 --timeout 300 run:app > ~/gro/app.log 2>&1 &
          
          # Wait a moment for the app to start
          sleep 3
          
          # Check if app is running
          if curl -f http://127.0.0.1:5000/ > /dev/null 2>&1; then
            echo "✅ Flask app is running successfully on port 5000"
          else
            echo "❌ Flask app failed to start"
            tail -20 ~/gro/app.log
            exit 1
          fi
          EOF